### ISSUE TITLE
ball of confusion crashes instantly loading this wave file

### ISSUE THREAD

**Issue by squinkylabs** [almostEric/Frequency-Domain-Manual#5]
some people were talking on Discord. Seemed like they would never log a bug, so I'll do it for them.

I can't get symbols, since I guess this is a closed source plugin. Here's what I got:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffcb59709e0 in strlen () from C:\WINDOWS\System32\msvcrt.dll
(gdb) bt
#0  0x00007ffcb59709e0 in strlen () from C:\WINDOWS\System32\msvcrt.dll
#1  0x00007ffc9145d045 in plugin!_ZN15frequencydomain3dsp5Seeds5_nextEv ()
   from D:\Rack\plugins\FrequencyDomain\plugin.dll
#2  0x00007ffc9145eac2 in plugin!_ZN15frequencydomain3dsp5Seeds5_nextEv ()
   from D:\Rack\plugins\FrequencyDomain\plugin.dll
#3  0x00007ffc9145ba78 in plugin!_ZN15frequencydomain3dsp5Seeds5_nextEv ()
   from D:\Rack\plugins\FrequencyDomain\plugin.dll
#4  0x00007ffc91462928 in plugin!_Z8snprintfPcyPKcz ()
   from D:\Rack\plugins\FrequencyDomain\plugin.dll
#5  0x00007ffc91471f4c in plugin!_ZN18BCDisplayWaveFiles4drawERKN4rack6widget6Widget8DrawArgsE () from D:\Rack\plugins\FrequencyDomain\plugin.dll
#6  0x00007ffc132bf341 in rack::widget::Widget::drawChild (
    this=this@entry=0x1ce0ad85b60, child=0x1ce0ad6a980, args=...,
    layer=layer@entry=0) at src/widget/Widget.cpp:311
#7  0x00007ffc132bf462 in rack::widget::Widget::draw (
    this=this@entry=0x1ce0ad85b60, args=...) at src/widget/Widget.cpp:280
#8  0x00007ffc13283e5a in rack::app::ModuleWidget::draw (this=0x1ce0ad85b60,
    args=...) at src/app/ModuleWidget.cpp:213
#9  0x00007ffc132bf341 in rack::widget::Widget::drawChild (
    this=this@entry=0x1ce0ab70a60, child=0x1ce0ad85b60, args=...,
    layer=layer@entry=0) at src/widget/Widget.cpp:311
#10 0x00007ffc132bf462 in rack::widget::Widget::draw (this=0x1ce0ab70a60,
    args=...) at src/widget/Widget.cpp:280
#11 0x00007ffc132bf341 in rack::widget::Widget::drawChild (
    this=this@entry=0x1ce0a2446a0, child=0x1ce0ab70a60, args=...,
    layer=layer@entry=0) at src/widget/Widget.cpp:311
#12 0x00007ffc132bf462 in rack::widget::Widget::draw (
```
I get this from just loading the enclosed wave. Reported said they had to load, then move the pitch knob. It's just a wav file, so remove the.jpeg extension
![fmpasd wav](https://user-images.githubusercontent.com/16314838/176987315-bd68fafe-7491-48f0-8472-00bf2c2a586b.jpeg)

**Comment by squinkylabs** [comment]
Here's a link to the Discord discussion: https://discord.com/channels/369861961514483723/370125417560145920/992602748363210783

**Comment by almostEric** [comment]
Not on that discord server, so I'd need an invite. But it sounds like they are not using a standard Serum wave file?
Which expects the wave to be some multiple of 2048 bytes. I'll add some error checking code
